apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: summarizer-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: queryIndexes
    value: |
      [
        {
          "name": "orgIndx",
          "indexes": [
            {
              "key": "id",
              "type": "TEXT"
            },
            {
              "key": "url",
              "type": "TEXT"
            },
            {
              "key": "url_hashed",
              "type": "TEXT"
            }
          ]
        }
      ] 